name: Test package

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [ created ]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    name: "${matrix.os} ${{ matrix.test }}_py${{ matrix.python-version }}"
    strategy:
      fail-fast: False
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        test: [ 'coveralls' ]
    runs-on: ${{ matrix.os }}
    env:
      NUMBA_DISABLE_JIT: 1
    steps:
      # Setup and installation
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: download data
        run: |
          sudo apt install zip   # Installs the zip package
          sudo apt install unzip # Installs the unzip package
          cd data
          wget https://surfdrive.surf.nl/files/index.php/s/rL452j1tsQyHc7w/download
          mv download download.zip
          unzip download.zip
          mv 2023_01_09_rp2023/* .
          cd ..
      - name: Install requirements
        run: |
          pip install -r extra_requirements/requirements-tests.txt
          python setup.py develop
      - name: Test package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBA_DISABLE_JIT: 1
        run: |
          pytest --cov RP2023 -v -n auto --nbmake 0*/*.ipynb --durations 0 --nb-coverage
          coveralls --service=github
      - name: goodbye
        run: echo "tests done, bye bye"
